import Media from './Media';
import Announcement from './Announcement';
import ImplementationPage from './ImplementationPage';

export default interface Implementation {
    id: number;
    name: string;
    logo?: string;
    url_webshop?: string;
    has_provider_terms_page: boolean;
    informal_communication?: boolean;
    email_color?: string;
    email_signature?: string;
    email_logo?: Media;
    email_signature_html?: string;
    email_color_default?: string;
    email_signature_default?: string;
    email_logo_default?: Media;
    title?: string;
    description?: string;
    organization_id?: number;
    description_html?: string;
    description_alignment?: string;
    email_from_name?: string;
    email_from_address?: string;
    digid_enabled?: boolean;
    digid_app_id?: string;
    digid_shared_secret?: string;
    digid_a_select_server?: string;
    overlay_type?: string;
    overlay_enabled?: boolean;
    header_text_color?: string;
    pre_check_url?: string;
    communication_type?: string;
    overlay_opacity?: number;
    banner?: Media;
    pre_check_banner?: Media;
    announcement?: Announcement;
    page_types?: Array<{
        key: string;
        type: string;
        blocks: boolean;
        faq: boolean;
        webshop_url: string;
        description_position_configurable: boolean;
    }>;
    show_home_map?: string;
    show_home_products?: string;
    show_provider_map?: string;
    show_providers_map?: string;
    show_office_map?: string;
    show_voucher_map?: string;
    show_product_map?: string;
    pages: Array<ImplementationPage>;
    pre_check_enabled: boolean;
    pre_check_title: string;
    pre_check_description: string;
    pre_check_banner_state: string;
    pre_check_banner_label: string;
    pre_check_banner_description: string;
    pre_check_banner_title: string;
}
